# image: https://hub.docker.com/r/bitnami/suitecrm
# docs: https://github.com/bitnami/bitnami-docker-suitecrm


version: '3.8'

services:
  suitecrm:
    image: docker.io/bitnami/suitecrm:${APP_VERSION}
    container_name: ${APP_NAME}
    ports:
      - '${APP_HTTP_PORT}:8080'
      - '${APP_HTTPS_PORT}:8443'
    environment:
      - SUITECRM_DATABASE_HOST=mysql
      - SUITECRM_DATABASE_PORT_NUMBER=${DB_MYSQL_PORT}
      - SUITECRM_DATABASE_USER=${DB_MYSQL_USER}
      - SUITECRM_DATABASE_NAME=${DB_MYSQL_NAME}
      - SUITECRM_DATABASE_PASSWORD=${DB_MYSQL_PASSWORD}
      - SUITECRM_USERNAME=${APP_USER}
      - SUITECRM_PASSWORD=${APP_PASSWORD}
      - SUITECRM_EMAIL=${APP_EMAIL}
      - SUITECRM_SKIP_BOOTSTRAP=no
      - ALLOW_EMPTY_PASSWORD=no
    volumes:
      - 'suitecrm:/bitnami/suitecrm'
    depends_on:
      - mysql

  mysql:
    image: mysql:${DB_MYSQL_VERSION}
    container_name: ${APP_NAME}-mysql
    command: --default-authentication-plugin=mysql_native_password    
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_MYSQL_PASSWORD}
      MYSQL_DATABASE: ${DB_MYSQL_NAME}
      MYSQL_USER: ${DB_MYSQL_USER}
      MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${DB_ES_VERSION}
    container_name: ${APP_NAME}-elasticsearch
    restart: unless-stopped
    ports:
        - ${DB_ES_HTTP_PORT}:9200
        - ${DB_ES_TCP_PORT}:9300
    environment:
        - discovery.type=single-node
        - xpack.security.enabled=false
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
networks:
  default:
    name: ${APP_NETWORK}
    external: true

volumes:
  mysql:
  suitecrm:
